### ISSUE TITLE
wait for the results

### ISSUE THREAD

**Issue by zdedenn** [Llamero/Local_Hough_Circle#6]
When used in a na IJ Macro, the Run("... command returns immediately, but the results are populated later. Is there a simple way to make ImageJ wait for the results?
Thanks!

**Comment by Llamero** [comment]
If you are having the code output images, then the following would be the easiest way to get the macro to wait:

images = nImages; //Count the number of currently open images
Run("....  //Run the Hough circle transform
while(images == nImages); //Wait while the number of open images is the same as before the transform
...do stuff 

A similar trick could be done using the number of reuslts:

results = nResults; //Count the number of results in the results table
Run("....  //Run the Hough circle transform
while(results == nResults); //Wait while the number of results is the same as before the transform
...do stuff

Hope this helps,
   Ben Smith

**Comment by zdedenn** [comment]
I 589
hey guys are going through 88
Sent from my Galaxy S5.

---------- Původní zpráva ----------
Od: Ben Smith 
Datum: 20. 9. 2018 v 19:51:05
Předmět: Re: [Llamero/Local_Hough_Circle] wait for the results (#6)


If you are having the code output images, then the following would be the 
easiest way to get the macro to wait:

images = nImages; //Count the number of currently open images
Run(".... //Run the Hough circle transform
while(images == nImages); //Wait while the number of open images is the same
as before the transform
...do stuff

A similar trick could be done using the number of reuslts:

results = nResults; //Count the number of currently open images
Run(".... //Run the Hough circle transform
while(results == nResults); //Wait until the number of open images is the 
same as before the transform
...do stuff

Hope this helps,
Ben Smith

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/Llamero/Local_Hough_Circle/issues/6#issuecomment-423370214)
, or mute the thread
